name: Demo GitHub Actions Workflow

on:
  push:

jobs:
  Discover-GitHub-Actions-Workflows:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world."
      - run: echo "Helloa sd world."
      - run: wait 100
      - run: echo "Helloa after time."
